// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: visualizer_data.proto
// Protobuf C++ Version: 6.33.2

#ifndef visualizer_5fdata_2eproto_2epb_2eh
#define visualizer_5fdata_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_visualizer_5fdata_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_visualizer_5fdata_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_visualizer_5fdata_2eproto;
}  // extern "C"
namespace senseauto {
namespace demo {
class CarState;
struct CarStateDefaultTypeInternal;
extern CarStateDefaultTypeInternal _CarState_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CarState_class_data_;
class FrameData;
struct FrameDataDefaultTypeInternal;
extern FrameDataDefaultTypeInternal _FrameData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FrameData_class_data_;
class Obstacle;
struct ObstacleDefaultTypeInternal;
extern ObstacleDefaultTypeInternal _Obstacle_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Obstacle_class_data_;
class Point3D;
struct Point3DDefaultTypeInternal;
extern Point3DDefaultTypeInternal _Point3D_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Point3D_class_data_;
}  // namespace demo
}  // namespace senseauto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace senseauto {
namespace demo {

// ===================================================================


// -------------------------------------------------------------------

class Point3D final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:senseauto.demo.Point3D) */ {
 public:
  inline Point3D() : Point3D(nullptr) {}
  ~Point3D() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Point3D* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Point3D));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Point3D(::google::protobuf::internal::ConstantInitialized);

  inline Point3D(const Point3D& from) : Point3D(nullptr, from) {}
  inline Point3D(Point3D&& from) noexcept
      : Point3D(nullptr, ::std::move(from)) {}
  inline Point3D& operator=(const Point3D& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point3D& operator=(Point3D&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Point3D& default_instance() {
    return *reinterpret_cast<const Point3D*>(
        &_Point3D_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Point3D& a, Point3D& b) { a.Swap(&b); }
  inline void Swap(Point3D* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point3D* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Point3D* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Point3D>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Point3D& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Point3D& from) { Point3D::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Point3D* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "senseauto.demo.Point3D"; }

  explicit Point3D(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Point3D(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Point3D& from);
  Point3D(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Point3D&& from) noexcept
      : Point3D(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // double x = 1;
  void clear_x() ;
  double x() const;
  void set_x(double value);

  private:
  double _internal_x() const;
  void _internal_set_x(double value);

  public:
  // double y = 2;
  void clear_y() ;
  double y() const;
  void set_y(double value);

  private:
  double _internal_y() const;
  void _internal_set_y(double value);

  public:
  // double z = 3;
  void clear_z() ;
  double z() const;
  void set_z(double value);

  private:
  double _internal_z() const;
  void _internal_set_z(double value);

  public:
  // @@protoc_insertion_point(class_scope:senseauto.demo.Point3D)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Point3D& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double x_;
    double y_;
    double z_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_visualizer_5fdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Point3D_class_data_;
// -------------------------------------------------------------------

class Obstacle final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:senseauto.demo.Obstacle) */ {
 public:
  inline Obstacle() : Obstacle(nullptr) {}
  ~Obstacle() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Obstacle* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Obstacle));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Obstacle(::google::protobuf::internal::ConstantInitialized);

  inline Obstacle(const Obstacle& from) : Obstacle(nullptr, from) {}
  inline Obstacle(Obstacle&& from) noexcept
      : Obstacle(nullptr, ::std::move(from)) {}
  inline Obstacle& operator=(const Obstacle& from) {
    CopyFrom(from);
    return *this;
  }
  inline Obstacle& operator=(Obstacle&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Obstacle& default_instance() {
    return *reinterpret_cast<const Obstacle*>(
        &_Obstacle_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Obstacle& a, Obstacle& b) { a.Swap(&b); }
  inline void Swap(Obstacle* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Obstacle* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Obstacle* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Obstacle>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Obstacle& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Obstacle& from) { Obstacle::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Obstacle* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "senseauto.demo.Obstacle"; }

  explicit Obstacle(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Obstacle(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Obstacle& from);
  Obstacle(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Obstacle&& from) noexcept
      : Obstacle(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTypeFieldNumber = 3,
    kPositionFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // string type = 3;
  void clear_type() ;
  const ::std::string& type() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_type(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_type();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_type();
  void set_allocated_type(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_type() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_type(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_type();

  public:
  // .senseauto.demo.Point3D position = 2;
  bool has_position() const;
  void clear_position() ;
  const ::senseauto::demo::Point3D& position() const;
  [[nodiscard]] ::senseauto::demo::Point3D* PROTOBUF_NULLABLE release_position();
  ::senseauto::demo::Point3D* PROTOBUF_NONNULL mutable_position();
  void set_allocated_position(::senseauto::demo::Point3D* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_position(::senseauto::demo::Point3D* PROTOBUF_NULLABLE value);
  ::senseauto::demo::Point3D* PROTOBUF_NULLABLE unsafe_arena_release_position();

  private:
  const ::senseauto::demo::Point3D& _internal_position() const;
  ::senseauto::demo::Point3D* PROTOBUF_NONNULL _internal_mutable_position();

  public:
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:senseauto.demo.Obstacle)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 36,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Obstacle& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr type_;
    ::senseauto::demo::Point3D* PROTOBUF_NULLABLE position_;
    ::int32_t id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_visualizer_5fdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Obstacle_class_data_;
// -------------------------------------------------------------------

class CarState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:senseauto.demo.CarState) */ {
 public:
  inline CarState() : CarState(nullptr) {}
  ~CarState() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CarState* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CarState));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CarState(::google::protobuf::internal::ConstantInitialized);

  inline CarState(const CarState& from) : CarState(nullptr, from) {}
  inline CarState(CarState&& from) noexcept
      : CarState(nullptr, ::std::move(from)) {}
  inline CarState& operator=(const CarState& from) {
    CopyFrom(from);
    return *this;
  }
  inline CarState& operator=(CarState&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CarState& default_instance() {
    return *reinterpret_cast<const CarState*>(
        &_CarState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CarState& a, CarState& b) { a.Swap(&b); }
  inline void Swap(CarState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CarState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CarState* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CarState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CarState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CarState& from) { CarState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CarState* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "senseauto.demo.CarState"; }

  explicit CarState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CarState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CarState& from);
  CarState(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CarState&& from) noexcept
      : CarState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPositionFieldNumber = 1,
    kHeadingFieldNumber = 2,
    kSpeedFieldNumber = 3,
    kSteeringAngleFieldNumber = 4,
  };
  // .senseauto.demo.Point3D position = 1;
  bool has_position() const;
  void clear_position() ;
  const ::senseauto::demo::Point3D& position() const;
  [[nodiscard]] ::senseauto::demo::Point3D* PROTOBUF_NULLABLE release_position();
  ::senseauto::demo::Point3D* PROTOBUF_NONNULL mutable_position();
  void set_allocated_position(::senseauto::demo::Point3D* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_position(::senseauto::demo::Point3D* PROTOBUF_NULLABLE value);
  ::senseauto::demo::Point3D* PROTOBUF_NULLABLE unsafe_arena_release_position();

  private:
  const ::senseauto::demo::Point3D& _internal_position() const;
  ::senseauto::demo::Point3D* PROTOBUF_NONNULL _internal_mutable_position();

  public:
  // double heading = 2;
  void clear_heading() ;
  double heading() const;
  void set_heading(double value);

  private:
  double _internal_heading() const;
  void _internal_set_heading(double value);

  public:
  // double speed = 3;
  void clear_speed() ;
  double speed() const;
  void set_speed(double value);

  private:
  double _internal_speed() const;
  void _internal_set_speed(double value);

  public:
  // double steering_angle = 4;
  void clear_steering_angle() ;
  double steering_angle() const;
  void set_steering_angle(double value);

  private:
  double _internal_steering_angle() const;
  void _internal_set_steering_angle(double value);

  public:
  // @@protoc_insertion_point(class_scope:senseauto.demo.CarState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CarState& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::senseauto::demo::Point3D* PROTOBUF_NULLABLE position_;
    double heading_;
    double speed_;
    double steering_angle_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_visualizer_5fdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CarState_class_data_;
// -------------------------------------------------------------------

class FrameData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:senseauto.demo.FrameData) */ {
 public:
  inline FrameData() : FrameData(nullptr) {}
  ~FrameData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FrameData* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FrameData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FrameData(::google::protobuf::internal::ConstantInitialized);

  inline FrameData(const FrameData& from) : FrameData(nullptr, from) {}
  inline FrameData(FrameData&& from) noexcept
      : FrameData(nullptr, ::std::move(from)) {}
  inline FrameData& operator=(const FrameData& from) {
    CopyFrom(from);
    return *this;
  }
  inline FrameData& operator=(FrameData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FrameData& default_instance() {
    return *reinterpret_cast<const FrameData*>(
        &_FrameData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(FrameData& a, FrameData& b) { a.Swap(&b); }
  inline void Swap(FrameData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FrameData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FrameData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FrameData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FrameData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FrameData& from) { FrameData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FrameData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "senseauto.demo.FrameData"; }

  explicit FrameData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FrameData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FrameData& from);
  FrameData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FrameData&& from) noexcept
      : FrameData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kObstaclesFieldNumber = 4,
    kCarStateFieldNumber = 3,
    kTimestampFieldNumber = 2,
    kFrameIdFieldNumber = 1,
  };
  // repeated .senseauto.demo.Obstacle obstacles = 4;
  int obstacles_size() const;
  private:
  int _internal_obstacles_size() const;

  public:
  void clear_obstacles() ;
  ::senseauto::demo::Obstacle* PROTOBUF_NONNULL mutable_obstacles(int index);
  ::google::protobuf::RepeatedPtrField<::senseauto::demo::Obstacle>* PROTOBUF_NONNULL mutable_obstacles();

  private:
  const ::google::protobuf::RepeatedPtrField<::senseauto::demo::Obstacle>& _internal_obstacles() const;
  ::google::protobuf::RepeatedPtrField<::senseauto::demo::Obstacle>* PROTOBUF_NONNULL _internal_mutable_obstacles();
  public:
  const ::senseauto::demo::Obstacle& obstacles(int index) const;
  ::senseauto::demo::Obstacle* PROTOBUF_NONNULL add_obstacles();
  const ::google::protobuf::RepeatedPtrField<::senseauto::demo::Obstacle>& obstacles() const;
  // .senseauto.demo.CarState car_state = 3;
  bool has_car_state() const;
  void clear_car_state() ;
  const ::senseauto::demo::CarState& car_state() const;
  [[nodiscard]] ::senseauto::demo::CarState* PROTOBUF_NULLABLE release_car_state();
  ::senseauto::demo::CarState* PROTOBUF_NONNULL mutable_car_state();
  void set_allocated_car_state(::senseauto::demo::CarState* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_car_state(::senseauto::demo::CarState* PROTOBUF_NULLABLE value);
  ::senseauto::demo::CarState* PROTOBUF_NULLABLE unsafe_arena_release_car_state();

  private:
  const ::senseauto::demo::CarState& _internal_car_state() const;
  ::senseauto::demo::CarState* PROTOBUF_NONNULL _internal_mutable_car_state();

  public:
  // double timestamp = 2;
  void clear_timestamp() ;
  double timestamp() const;
  void set_timestamp(double value);

  private:
  double _internal_timestamp() const;
  void _internal_set_timestamp(double value);

  public:
  // int32 frame_id = 1;
  void clear_frame_id() ;
  ::int32_t frame_id() const;
  void set_frame_id(::int32_t value);

  private:
  ::int32_t _internal_frame_id() const;
  void _internal_set_frame_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:senseauto.demo.FrameData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FrameData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::senseauto::demo::Obstacle > obstacles_;
    ::senseauto::demo::CarState* PROTOBUF_NULLABLE car_state_;
    double timestamp_;
    ::int32_t frame_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_visualizer_5fdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FrameData_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Point3D

// double x = 1;
inline void Point3D::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double Point3D::x() const {
  // @@protoc_insertion_point(field_get:senseauto.demo.Point3D.x)
  return _internal_x();
}
inline void Point3D::set_x(double value) {
  _internal_set_x(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:senseauto.demo.Point3D.x)
}
inline double Point3D::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void Point3D::_internal_set_x(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// double y = 2;
inline void Point3D::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double Point3D::y() const {
  // @@protoc_insertion_point(field_get:senseauto.demo.Point3D.y)
  return _internal_y();
}
inline void Point3D::set_y(double value) {
  _internal_set_y(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:senseauto.demo.Point3D.y)
}
inline double Point3D::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void Point3D::_internal_set_y(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// double z = 3;
inline void Point3D::clear_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double Point3D::z() const {
  // @@protoc_insertion_point(field_get:senseauto.demo.Point3D.z)
  return _internal_z();
}
inline void Point3D::set_z(double value) {
  _internal_set_z(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:senseauto.demo.Point3D.z)
}
inline double Point3D::_internal_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z_;
}
inline void Point3D::_internal_set_z(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = value;
}

// -------------------------------------------------------------------

// CarState

// .senseauto.demo.Point3D position = 1;
inline bool CarState::has_position() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.position_ != nullptr);
  return value;
}
inline void CarState::clear_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.position_ != nullptr) _impl_.position_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::senseauto::demo::Point3D& CarState::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::senseauto::demo::Point3D* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::senseauto::demo::Point3D&>(::senseauto::demo::_Point3D_default_instance_);
}
inline const ::senseauto::demo::Point3D& CarState::position() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:senseauto.demo.CarState.position)
  return _internal_position();
}
inline void CarState::unsafe_arena_set_allocated_position(
    ::senseauto::demo::Point3D* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = reinterpret_cast<::senseauto::demo::Point3D*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:senseauto.demo.CarState.position)
}
inline ::senseauto::demo::Point3D* PROTOBUF_NULLABLE CarState::release_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::senseauto::demo::Point3D* released = _impl_.position_;
  _impl_.position_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::senseauto::demo::Point3D* PROTOBUF_NULLABLE CarState::unsafe_arena_release_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:senseauto.demo.CarState.position)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::senseauto::demo::Point3D* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::senseauto::demo::Point3D* PROTOBUF_NONNULL CarState::_internal_mutable_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.position_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::senseauto::demo::Point3D>(GetArena());
    _impl_.position_ = reinterpret_cast<::senseauto::demo::Point3D*>(p);
  }
  return _impl_.position_;
}
inline ::senseauto::demo::Point3D* PROTOBUF_NONNULL CarState::mutable_position()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::senseauto::demo::Point3D* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:senseauto.demo.CarState.position)
  return _msg;
}
inline void CarState::set_allocated_position(::senseauto::demo::Point3D* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.position_ = reinterpret_cast<::senseauto::demo::Point3D*>(value);
  // @@protoc_insertion_point(field_set_allocated:senseauto.demo.CarState.position)
}

// double heading = 2;
inline void CarState::clear_heading() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heading_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double CarState::heading() const {
  // @@protoc_insertion_point(field_get:senseauto.demo.CarState.heading)
  return _internal_heading();
}
inline void CarState::set_heading(double value) {
  _internal_set_heading(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:senseauto.demo.CarState.heading)
}
inline double CarState::_internal_heading() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heading_;
}
inline void CarState::_internal_set_heading(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heading_ = value;
}

// double speed = 3;
inline void CarState::clear_speed() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.speed_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double CarState::speed() const {
  // @@protoc_insertion_point(field_get:senseauto.demo.CarState.speed)
  return _internal_speed();
}
inline void CarState::set_speed(double value) {
  _internal_set_speed(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:senseauto.demo.CarState.speed)
}
inline double CarState::_internal_speed() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.speed_;
}
inline void CarState::_internal_set_speed(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.speed_ = value;
}

// double steering_angle = 4;
inline void CarState::clear_steering_angle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.steering_angle_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline double CarState::steering_angle() const {
  // @@protoc_insertion_point(field_get:senseauto.demo.CarState.steering_angle)
  return _internal_steering_angle();
}
inline void CarState::set_steering_angle(double value) {
  _internal_set_steering_angle(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:senseauto.demo.CarState.steering_angle)
}
inline double CarState::_internal_steering_angle() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.steering_angle_;
}
inline void CarState::_internal_set_steering_angle(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.steering_angle_ = value;
}

// -------------------------------------------------------------------

// Obstacle

// int32 id = 1;
inline void Obstacle::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t Obstacle::id() const {
  // @@protoc_insertion_point(field_get:senseauto.demo.Obstacle.id)
  return _internal_id();
}
inline void Obstacle::set_id(::int32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:senseauto.demo.Obstacle.id)
}
inline ::int32_t Obstacle::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void Obstacle::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// .senseauto.demo.Point3D position = 2;
inline bool Obstacle::has_position() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.position_ != nullptr);
  return value;
}
inline void Obstacle::clear_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.position_ != nullptr) _impl_.position_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::senseauto::demo::Point3D& Obstacle::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::senseauto::demo::Point3D* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::senseauto::demo::Point3D&>(::senseauto::demo::_Point3D_default_instance_);
}
inline const ::senseauto::demo::Point3D& Obstacle::position() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:senseauto.demo.Obstacle.position)
  return _internal_position();
}
inline void Obstacle::unsafe_arena_set_allocated_position(
    ::senseauto::demo::Point3D* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = reinterpret_cast<::senseauto::demo::Point3D*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:senseauto.demo.Obstacle.position)
}
inline ::senseauto::demo::Point3D* PROTOBUF_NULLABLE Obstacle::release_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::senseauto::demo::Point3D* released = _impl_.position_;
  _impl_.position_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::senseauto::demo::Point3D* PROTOBUF_NULLABLE Obstacle::unsafe_arena_release_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:senseauto.demo.Obstacle.position)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::senseauto::demo::Point3D* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::senseauto::demo::Point3D* PROTOBUF_NONNULL Obstacle::_internal_mutable_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.position_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::senseauto::demo::Point3D>(GetArena());
    _impl_.position_ = reinterpret_cast<::senseauto::demo::Point3D*>(p);
  }
  return _impl_.position_;
}
inline ::senseauto::demo::Point3D* PROTOBUF_NONNULL Obstacle::mutable_position()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::senseauto::demo::Point3D* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:senseauto.demo.Obstacle.position)
  return _msg;
}
inline void Obstacle::set_allocated_position(::senseauto::demo::Point3D* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.position_ = reinterpret_cast<::senseauto::demo::Point3D*>(value);
  // @@protoc_insertion_point(field_set_allocated:senseauto.demo.Obstacle.position)
}

// string type = 3;
inline void Obstacle::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Obstacle::type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:senseauto.demo.Obstacle.type)
  return _internal_type();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Obstacle::set_type(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.type_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:senseauto.demo.Obstacle.type)
}
inline ::std::string* PROTOBUF_NONNULL Obstacle::mutable_type()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:senseauto.demo.Obstacle.type)
  return _s;
}
inline const ::std::string& Obstacle::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.type_.Get();
}
inline void Obstacle::_internal_set_type(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Obstacle::_internal_mutable_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.type_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Obstacle::release_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:senseauto.demo.Obstacle.type)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.type_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.type_.Set("", GetArena());
  }
  return released;
}
inline void Obstacle::set_allocated_type(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.type_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.type_.IsDefault()) {
    _impl_.type_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:senseauto.demo.Obstacle.type)
}

// -------------------------------------------------------------------

// FrameData

// int32 frame_id = 1;
inline void FrameData::clear_frame_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.frame_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t FrameData::frame_id() const {
  // @@protoc_insertion_point(field_get:senseauto.demo.FrameData.frame_id)
  return _internal_frame_id();
}
inline void FrameData::set_frame_id(::int32_t value) {
  _internal_set_frame_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:senseauto.demo.FrameData.frame_id)
}
inline ::int32_t FrameData::_internal_frame_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.frame_id_;
}
inline void FrameData::_internal_set_frame_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.frame_id_ = value;
}

// double timestamp = 2;
inline void FrameData::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double FrameData::timestamp() const {
  // @@protoc_insertion_point(field_get:senseauto.demo.FrameData.timestamp)
  return _internal_timestamp();
}
inline void FrameData::set_timestamp(double value) {
  _internal_set_timestamp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:senseauto.demo.FrameData.timestamp)
}
inline double FrameData::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void FrameData::_internal_set_timestamp(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

// .senseauto.demo.CarState car_state = 3;
inline bool FrameData::has_car_state() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.car_state_ != nullptr);
  return value;
}
inline void FrameData::clear_car_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.car_state_ != nullptr) _impl_.car_state_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::senseauto::demo::CarState& FrameData::_internal_car_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::senseauto::demo::CarState* p = _impl_.car_state_;
  return p != nullptr ? *p : reinterpret_cast<const ::senseauto::demo::CarState&>(::senseauto::demo::_CarState_default_instance_);
}
inline const ::senseauto::demo::CarState& FrameData::car_state() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:senseauto.demo.FrameData.car_state)
  return _internal_car_state();
}
inline void FrameData::unsafe_arena_set_allocated_car_state(
    ::senseauto::demo::CarState* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.car_state_);
  }
  _impl_.car_state_ = reinterpret_cast<::senseauto::demo::CarState*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:senseauto.demo.FrameData.car_state)
}
inline ::senseauto::demo::CarState* PROTOBUF_NULLABLE FrameData::release_car_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::senseauto::demo::CarState* released = _impl_.car_state_;
  _impl_.car_state_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::senseauto::demo::CarState* PROTOBUF_NULLABLE FrameData::unsafe_arena_release_car_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:senseauto.demo.FrameData.car_state)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::senseauto::demo::CarState* temp = _impl_.car_state_;
  _impl_.car_state_ = nullptr;
  return temp;
}
inline ::senseauto::demo::CarState* PROTOBUF_NONNULL FrameData::_internal_mutable_car_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.car_state_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::senseauto::demo::CarState>(GetArena());
    _impl_.car_state_ = reinterpret_cast<::senseauto::demo::CarState*>(p);
  }
  return _impl_.car_state_;
}
inline ::senseauto::demo::CarState* PROTOBUF_NONNULL FrameData::mutable_car_state()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::senseauto::demo::CarState* _msg = _internal_mutable_car_state();
  // @@protoc_insertion_point(field_mutable:senseauto.demo.FrameData.car_state)
  return _msg;
}
inline void FrameData::set_allocated_car_state(::senseauto::demo::CarState* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.car_state_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.car_state_ = reinterpret_cast<::senseauto::demo::CarState*>(value);
  // @@protoc_insertion_point(field_set_allocated:senseauto.demo.FrameData.car_state)
}

// repeated .senseauto.demo.Obstacle obstacles = 4;
inline int FrameData::_internal_obstacles_size() const {
  return _internal_obstacles().size();
}
inline int FrameData::obstacles_size() const {
  return _internal_obstacles_size();
}
inline void FrameData::clear_obstacles() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.obstacles_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::senseauto::demo::Obstacle* PROTOBUF_NONNULL FrameData::mutable_obstacles(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:senseauto.demo.FrameData.obstacles)
  return _internal_mutable_obstacles()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::senseauto::demo::Obstacle>* PROTOBUF_NONNULL FrameData::mutable_obstacles()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:senseauto.demo.FrameData.obstacles)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_obstacles();
}
inline const ::senseauto::demo::Obstacle& FrameData::obstacles(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:senseauto.demo.FrameData.obstacles)
  return _internal_obstacles().Get(index);
}
inline ::senseauto::demo::Obstacle* PROTOBUF_NONNULL FrameData::add_obstacles()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::senseauto::demo::Obstacle* _add =
      _internal_mutable_obstacles()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:senseauto.demo.FrameData.obstacles)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::senseauto::demo::Obstacle>& FrameData::obstacles() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:senseauto.demo.FrameData.obstacles)
  return _internal_obstacles();
}
inline const ::google::protobuf::RepeatedPtrField<::senseauto::demo::Obstacle>&
FrameData::_internal_obstacles() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.obstacles_;
}
inline ::google::protobuf::RepeatedPtrField<::senseauto::demo::Obstacle>* PROTOBUF_NONNULL
FrameData::_internal_mutable_obstacles() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.obstacles_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace demo
}  // namespace senseauto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // visualizer_5fdata_2eproto_2epb_2eh
